apiVersion: v2
name: ray-operator
description: Ray Operator with ServiceAccounts for model storage
version: 0.1.0
dependencies:
  - name: kuberay-operator
    version: "1.2.2"
    repository: oci://ghcr.io/amediomediagroup/charts/upstream/ray
