{
 "title": "webapp_metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rust application metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP requests per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(rocket_http_requests_total{endpoint!=\"/metrics\"}[1h]) / (60 * 60)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests number for the last minute",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rocket_http_requests_total{endpoint!=\"/metrics\"}[2m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(rocket_http_requests_duration_seconds_bucket{endpoint!=\"/metrics\"}[$__range])) * 10000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rocket_http_requests_duration_seconds_sum) / \n sum(rocket_http_requests_duration_seconds_count)) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{k8s_container_name=\"rust-app\"}[1m])",
     "legendFormat": "process"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{k8s_container_name=\"rust-app\"}[1m])) by (name)",
     "legendFormat": "container"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{k8s_container_name=\"rust-app\"} / 1024 / 1024",
     "legendFormat": "process"
    },
    {
     "expr": "container_memory_usage_bytes{k8s_container_name=\"rust-app\"} / 1024 / 1024",
     "legendFormat": "container"
    }
   ]
  }
 ]
}